[project]
name = "ingest-framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-cloud-bigquery>=3.31.0",
    "pyyaml>=6.0.2",
    "ruff>=0.11.6",
]
